### PR TITLE
rename + travis + tests

### PR DESCRIPTION
**Pull request by tanner0101**
Renames InterchangeData -> StructuredData as well as adds some important stuff like `.swift-version`, Xcodeproj, and `.travis.yml`.

Also added Tests with an example test in there.

Whoever has access to Zewo on Travis should enable this repo. I can do it if I'm added as a contributor I think. :)

### CODE REVIEW

**Comment by paulofaria** [comment]
do you need the Xcode project?

**Comment by tanner0101** [comment]
The project can be generated by running `swift build -X`, but I've been including them in my repos because you can still put shared schemes in there and add runtimes arguments, etc.

This is especially helpful if the project produces extraneous executables that could confuse someone. 

I can remove it if you don't want it to be included.

**Comment by paulofaria** [comment]
yeah I was wondering about that, the project created by SPM. what happens if you run `swift build -X` when a project already exists?

> extraneous executables
> can you give me examples?

**Comment by tanner0101** [comment]
It works nicely. It will just quietly overwrite the parts that changed, but leave the shared schema.

> extraneous executables
> can you give me examples?

Vapor produces a `VaporDev` and `Generator` executable. The `VaporDev` is a module with a `main.swift` that uses `Vapor`. That way, we have a shared "example project" that we can use as we build Vapor.

I think C7 and S4 could benefit from one of these example modules. In this case, you want to ensure that the Xcode Schema for C7 and S4 include their respective example modules (this happens by default) but , because of a bug with excludes in SPM, the example module for C7 will get included in S4's schemas by default.  This could be desirable or could not be. But, by committing the Xcodeproj and setting the schemas to shared, you can choose what gets included.

**Pull request merged**
